### ISSUE TITLE
ouster ros bags not working

### ISSUE THREAD

**Issue by rfsch** [cruise-automation/webviz#162]
Hi 

I cannot drop the ouster ros bag files into webviz 
http://data.ouster.io/sample-data-2018-08-29/index.html

thanks

**Comment by jtbandes** [comment]
Hi, thanks for your interest in webviz! It looks like these bags each only have two topics, is that right?

![image](https://user-images.githubusercontent.com/14237/60031660-0238a300-965a-11e9-88b4-5658ac54d75a.png)


My first guess would be that the topics are not correctly handled because they don't start with a `/`. (Webviz might be making some incorrect assumptions there, because the data we usually work with has universally `/`-prefixed topic names.) As a quick workaround, you can try renaming the topics so they start with `/`.

**Comment by andre-nguyen** [comment]
The bags are not handled because the topics are non-standard. They are the raw dumps from the ouster lidar, you have to convert those to point clouds and save the point clouds as bags.

**Comment by janpaul123** [comment]
I'm going through some old tickets to clean them up: indeed we currently only support the standard [`sensor_msgs/PointCloud2`](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/PointCloud2.html) message type for point clouds. So just convert the bag to use those and it should work. Let us know if you have any more issues!

**Comment by zlg9folira** [comment]
I have `/os1_cloud_points/points` of type `sensor_msgs::PointCloud2` in my bag files. I am trying to visualize through 3D panel inside WebWiz. It however does nothing. There is a toggle point next to topic name in the panel. When I select that, a red `error` sign appears:
`Missing transform to root transform map`

Any idea ?

**Comment by vidaaudrey** [comment]
Hi @zlg9folira, at the right side of the 3D panel, you could choose which the root frame and all the other markers will be rendered according to the correct root frame. As for why do we need `/tf`, here is the link to read more: http://wiki.ros.org/tf#:~:text=Package%20Summary&text=tf%20is%20a%20package%20that,any%20desired%20point%20in%20time.
